import Foundation

/// 「路由表」页面相关文案的英文对照。键是中文原文。
let englishStringsRoutes: [String: String] = [
    // MARK: - 页面与分组
    "路由表": "Routes",
    "正在读取路由表…": "Reading the routing table…",
    "读不到路由表，点下面的「刷新」重试": "Couldn't read the routing table. Click Refresh below to try again.",
    "没有匹配的路由": "No matching routes",
    "搜索路由": "Search routes",
    "只显示 IPv4 路由。这里加的路由是临时的，不会写进任何配置": "IPv4 only. Routes added here are temporary and are not written into any profile.",
    "默认路由": "Default Route",
    "整机的出口。删掉之后，不匹配其他路由的流量会立刻中断": "The machine's default gateway. Delete it and every packet that matches no other route stops immediately.",
    "下一跳是具体地址的路由：可能是手动加的，也可能是 VPN 下发的": "Routes whose next hop is a concrete address — added by hand or pushed by a VPN.",
    "接口直连": "Interface Link",
    "系统按接口地址自动生成的直连网段，一般不用管": "Directly connected networks generated from the interface address. Usually nothing to do here.",
    "本机与组播": "Local & Multicast",
    "回环、组播和广播，系统自带，删了通常马上重建": "Loopback, multicast, and broadcast. Supplied by the system and normally recreated right away.",

    // MARK: - 行
    "下一跳 %@": "Next hop %@",
    "接口 %@": "Interface %@",
    "来自配置「%@」": "From profile \"%@\"",
    "VPN": "VPN",

    // MARK: - 删除确认
    "仍要删除": "Delete Anyway",
    "删除默认路由": "Delete Default Route",
    "删除接口直连路由": "Delete Interface Link Route",
    "删除系统路由": "Delete System Route",
    "删除 VPN 路由": "Delete VPN Route",
    "default 是整机的默认出口，当前走 %@。删掉后所有不匹配其他路由的流量——上网、iCloud、App Store——会立刻中断。删除后可以在下面的「本次删除」里加回来。": "default is the machine's default gateway and currently points at %@. Deleting it immediately cuts off everything that matches no other route — browsing, iCloud, the App Store. You can put it back from Deleted This Session below.",
    "%@ 是接口 %@ 的直连网段，由系统随接口地址自动生成。删掉后本机可能连该网段里的设备（包括网关）都访问不了；系统通常会在接口状态变化时重新生成它。": "%@ is the directly connected network for interface %@, generated by the system from the interface address. Deleting it may cut this machine off from every device on that network, including the gateway. The system usually regenerates it when the interface state changes.",
    "%@ 是系统自带的本机或组播路由，删掉通常没有意义，系统会自己重建。": "%@ is a local or multicast route provided by the system. Deleting it usually achieves nothing because the system recreates it.",
    "%@ 走的是 %@ 隧道，多半由 VPN 下发。删掉后这个网段的流量会改走其他路由或直接失败。": "%@ runs over the %@ tunnel and was most likely pushed by a VPN. Deleting it makes that network's traffic take another route or fail outright.",

    // MARK: - 提示条与「本次删除」
    "撤回": "Undo",
    "本次删除": "Deleted This Session",
    "这次运行里删掉的路由，点「还原」加回去。关掉应用后这份记录就没了": "Routes deleted during this run. Click Restore to put one back. This list disappears once you quit the app.",
    "还原失败：%@": "Restore failed: %@",
    "没能还原": "Not restored",

    // MARK: - 表单
    "路由": "Route",
    "新增路由": "Add Route",
    "修改路由": "Edit Route",
    "新增": "Add",
    "要写进路由表的目标地址，如 10.100.0.0": "The destination to write into the routing table, e.g. 10.100.0.0",
    "可以填 255.255.255.0，也可以只填前缀长度 24": "Either 255.255.255.0 or just the prefix length, 24",
    "这个网段的流量交给谁，通常是本机所在网段的网关": "Who handles traffic for this network — usually the gateway of this machine's own subnet",
    "metric": "metric",
    "留空表示不设置。路由表里看不到当前跃点数，这里填的是这次要写进去的值": "Leave empty for no metric. The routing table doesn't show the current hop count, so this is the value written now.",
    "前缀长度只能是 1–32。默认路由（前缀 0）不能在这里增删改，要换默认网关请到「系统设置 → 网络」或「配置管理」里改。": "Prefix length must be 1–32. The default route (prefix 0) cannot be added, changed, or removed here; change your default gateway in System Settings → Network or in Profiles.",
    "或填 24": "or 24",
    "metric 要填一个整数，留空表示不设置": "metric must be an integer; leave it empty for none",
    "不支持在这里设置前缀 0（默认路由），要换默认网关请到「系统设置 → 网络」或「配置管理」里改。": "Prefix 0 (the default route) cannot be set here. Change your default gateway in System Settings → Network or in Profiles.",
    "会先删掉现在的 %@，再按下面的值加一条": "The current %@ is deleted first, then a route is added with the values below",
    "临时写进系统路由表，不会保存到任何配置里": "Written into the system routing table temporarily; not saved into any profile",

    // MARK: - RouteManager
    "%@ 的掩码 %@ 不是合法掩码，无法删除这条路由": "%@ has an invalid mask (%@), so this route cannot be deleted",
    "%@ 已经不在路由表里了": "%@ is no longer in the routing table",
    "route delete %@ 没有生效，这条路由还在表里": "route delete %@ had no effect; the route is still in the table",
    "route add %@ 没有生效，这条路由不在表里": "route add %@ had no effect; the route is not in the table",
    "%@ 的掩码 %@ 不是合法掩码，无法还原这条路由": "%@ has an invalid mask (%@), so this route cannot be restored",
    "%@ 已被系统重新生成，无需还原": "%@ was regenerated by the system; there is nothing to restore",
    "%@ 是接口直连路由，但路由表里没给出接口名，无法还原": "%@ is an interface link route, but the routing table gave no interface name, so it cannot be restored",
    "%@ 在路由表里没有下一跳，无法还原": "%@ has no next hop in the routing table, so it cannot be restored",
    "已还原 %@": "Restored %@",

    // MARK: - 日志
    "开始删除路由 %@": "Deleting route %@",
    "开始还原路由 %@": "Restoring route %@",
    "开始新增路由 %@": "Adding route %@",
    "开始修改路由 %@": "Editing route %@",
    "路由操作失败（%@）：%@": "Route operation failed (%@): %@",
    "%@；已把原来的 %@ 加回去": "%@; the original %@ was added back",
    "回滚路由 %@ 也失败了：%@": "Rolling back route %@ also failed: %@",
    "%@；原来的 %@ 也没能加回去，请到路由表里手动补一条": "%@; the original %@ could not be added back either — add it back manually in Routes"
]
