import Foundation

/// 「接口概览 / 自动化规则」相关文案的英文对照。键是中文原文。
let englishStringsOverview: [String: String] = [
    // 接口概览
    "网络接口": "Network Interfaces",
    "绿色圆点表示链路已建立：网线已插入并完成协商，或 Wi-Fi 已关联到网络": "A green dot means the link is up: the cable is plugged in and negotiated, or Wi-Fi is associated with a network",
    "正在读取网络接口…": "Loading interfaces…",
    "没有匹配的接口": "No matching interfaces",
    "无法写入配置": "Cannot Write Configuration",
    "接口 %@ 在系统里没有对应的网络服务，请先到「系统设置 → 网络」里添加": "Interface %@ has no matching network service. Add one in System Settings → Network first",
    "当前 IP": "Current IP",
    "配置方式": "IP Assignment",
    "切换配置": "Switch Profile",
    "类型 %@": "Type: %@",
    "网络服务 %@": "Network Service: %@",
    "未设置": "Not Set",
    "接口未连接": "Interface Not Connected",
    "未匹配到已保存的配置": "No Matching Saved Profile",
    "当前 %@，可在下面新增一份配置来固化这套参数": "Currently %@. Add a profile below to lock in these settings",
    "需要授权": "Permission Required",
    "修改 IP 和路由需要 root 权限，装一次免密授权之后就不会再弹密码框": "Changing the IP and routes requires root. Install passwordless authorization once and you won't be prompted again",
    "尚未安装 sudo 免密授权": "Passwordless sudo Not Installed",
    "没有它的话，自动应用会因为权限不足而失败。装一次即可，之后开关机都不再需要密码。": "Without it, Auto Apply fails due to insufficient permissions. Install it once and you won't need a password again, even after restarting",

    // 自动化规则
    "只在接口「未连接 → 已连接」的那一刻触发，已经连着的接口不会被动改写": "Triggers only at the moment an interface goes from Not Connected to Connected; interfaces that are already connected are never rewritten",
    "启用自动应用": "Enable Auto Apply",
    "总开关。关掉之后，所有标记为自动应用的配置都不会再自动生效": "Master switch. When off, no profile marked for auto apply takes effect automatically",
    "启动时校正一次": "Reconcile on Launch",
    "开机或重新打开应用后，把已连接接口的配置对齐到自动配置（等系统网络就绪约 5 秒后执行）": "After a restart or relaunch, align connected interfaces to their auto-apply profiles (runs about 5 seconds after the network is ready)",
    "连接事件防抖": "Connection Event Debounce",
    "接口插上后系统还会陆续下发配置，等 %@ 再动手，避免打断系统自己的流程": "After an interface is plugged in, the system keeps applying settings; wait %@ before acting so the system's own process isn't interrupted",
    "不用插拔网线，现在就把所有已连接接口对齐一遍": "Align all connected interfaces right now, without unplugging the cable",
    "现在校正": "Reconcile Now",
    "手动校正": "Manual reconcile",
    "各接口的自动配置": "Auto-Apply Profile per Interface",
    "每个接口最多只能有一份配置被标记为自动应用，互不影响": "Each interface can have at most one profile marked for auto apply; they don't affect one another",
    "去新建": "New Profile",
    "不自动应用": "No Auto-Apply",
    "目标：%@": "Target: %@",
    "等待接口连接，连上后会自动写入「%@」": "Waiting for the interface to connect; %@ will be applied automatically once it does",
    "缺少 root 权限，无法自动应用「%@」": "Missing root permission; cannot auto-apply %@",
    "当前配置已符合「%@」": "The current configuration already matches %@",
    "当前配置与「%@」不一致，插拔一次网线或点「现在校正」即可写入": "The current configuration doesn't match %@. Unplug and replug the cable, or click Reconcile Now, to apply it",
    "改 IP、增删路由都要 root 权限。装一次免密授权，之后自动应用才不会静默失败": "Changing IPs and adding or removing routes requires root. Install passwordless authorization once so Auto Apply doesn't fail silently",
    "免密授权已就绪": "Passwordless Authorization Ready",
    "尚未安装免密授权": "Passwordless Authorization Not Installed",
    "networksetup 与 route 已可通过 sudo 免密执行": "networksetup and route can now run through passwordless sudo",
    "没有授权时，自动应用会因为没有权限而失败，配置也写不进去": "Without authorization, Auto Apply fails due to missing permissions and profiles can't be written",
    "%d 秒": "%d s",
    "%.1f 秒": "%.1f s",
    "网络服务优先级": "Network Service Priority",
    "系统按这个顺序决定用哪条链路收发数据，排在上面的优先。改完点「应用顺序」写入；插拔网卡带出新服务后要再应用一次": "The system uses this order to decide which link carries traffic, with the topmost entry winning. Click Apply Order to write it; re-apply after plugging in an adapter introduces a new service.",
    "第 %d 位": "Position %d",
    "无对应设备": "No matching device",
    "已停用": "Disabled",
    "上移": "Move Up",
    "下移": "Move Down",
    "与系统当前顺序不一致，点「应用顺序」写入": "Differs from the system's current order; click Apply Order to write it.",
    "与系统当前顺序一致": "Matches the system's current order.",
    "放弃自定义顺序": "Discard Custom Order",
    "正在写入…": "Writing…",
    "应用顺序": "Apply Order",
    "正在读取网络服务…": "Reading network services…",
    "当前配置已符合「%@」，但还没排到服务顺序第一位": "The current configuration already matches %@, but the service is not yet first in the service order.",
    "不使用配置（交还系统）": "No Profile (Return to System)",
    "会把 %@ 交还系统：IP 切回 DHCP、DNS 改自动获取，并删掉本应用写进去的静态路由。该接口的自动应用也会一起关掉。": "This returns %@ to the system: IP goes back to DHCP, DNS becomes automatic, and the static routes written by this app are removed. Auto apply for this interface is turned off as well.",
    "交还系统": "Return to System",
]
