import Foundation

/// 「配置管理 / 配置编辑器」相关文案的英文对照。键是中文原文。
let englishStringsProfiles: [String: String] = [
    "新建配置": "New Profile",
    "编辑配置": "Edit Profile",
    "基本信息": "Basic Information",
    "配置会写入所绑定的这个网络接口": "This profile is written to the network interface it is bound to.",
    "名称": "Name",
    "给这套配置起个好认的名字": "Give this profile an easy-to-recognize name.",
    "例如：公司内网": "e.g. Office Network",
    "绑定接口": "Bound Interface",
    "配置文件里用 BSD 设备名匹配，如 en0": "Profiles match by BSD device name, such as en0.",
    "请选择": "Choose…",
    "%@（当前不在系统中）": "%@ (not currently in the system)",

    "选择地址是手工填写还是由 DHCP 服务器下发": "Choose whether the address is entered manually or provided by a DHCP server.",
    "IP 获取方式": "IP Address Source",
    "IP 地址": "IP Address",
    "必填": "Required",
    "格式不正确": "Invalid format",
    "子网掩码": "Subnet Mask",
    "必须是连续的网络位，如 255.255.255.0": "Must be contiguous network bits, e.g. 255.255.255.0.",
    "网关": "Gateway",
    "由 DHCP 服务器分配": "Assigned by DHCP Server",
    "应用时执行 networksetup -setdhcp：IP、掩码、网关全部由服务器决定，本机填的值不参与。上面填过的值会保留，切回「手动」时还能用": "Applies networksetup -setdhcp: IP, mask, and gateway are all determined by the server, and locally entered values are ignored. Values entered above are kept and remain available when you switch back to Manual.",

    "DNS 获取方式": "DNS Source",
    "DNS 和 IP 的来源相互独立：用 DHCP 拿地址，同样可以指定固定 DNS": "DNS and IP sources are independent: you can get an address via DHCP and still specify fixed DNS servers.",
    "交给系统获取": "Provided by the System",
    "应用时会清空手动 DNS 列表（networksetup -setdnsservers <服务> Empty）。已填写的地址会保留，切回「手动指定」时还能用": "Applies networksetup -setdnsservers <service> Empty, clearing the manual DNS list. Entered addresses are kept and remain available when you switch back to Manual.",
    "IP 是手动填写的，DHCP 服务器不会下发 DNS。这个组合下系统没有任何 DNS 服务器，域名解析会失败，建议改成「手动指定」。": "IP is entered manually, so the DHCP server will not provide DNS. With this combination the system has no DNS servers and name resolution will fail. Consider switching to Manual.",
    "还没有 DNS 地址": "No DNS Addresses Yet",
    "手动指定至少要填一个，否则应用时会失败": "At least one address is required in Manual mode, or applying will fail.",
    "添加 DNS": "Add DNS",
    "移除这条 DNS": "Remove this DNS entry",

    "静态路由": "Static Route",
    "应用时会先查路由表：不存在就添加，下一跳不一致就先删除再加": "On apply, the routing table is checked first: missing routes are added, and routes with a different next hop are removed and re-added.",
    "没有静态路由": "No Static Routes",
    "如果只是切换 IP 和网关，这里可以留空": "Leave empty if you only need to switch IP and gateway.",
    "添加路由": "Add Route",
    "目的网段": "Destination",
    "掩码": "Mask",
    "移除这条路由": "Remove this route",
    "下一跳": "Next Hop",
    "可选": "Optional",

    "自动化": "Automation",
    "设为该接口的自动应用配置": "Set as the Auto Apply profile for this interface",
    "自动": "Auto",
    "还有 %d 项需要修正，否则应用时会失败": "%d items must be fixed, or applying will fail.",
    "取消": "Cancel",
    "创建": "Create",
    "保存": "Save",
    "开启后，接口从「未连接」变为「已连接」时会自动写入这套配置": "When enabled, this profile is written automatically when the interface goes from Not Connected to Connected.",
    "保存后会同时关闭同一接口下「%@」的自动应用（每个接口只能有一份）": "Saving will also turn off Auto Apply for \"%@\" on the same interface (only one profile per interface can have it on).",
    "已开启：接口连上时自动应用这套配置": "On: this profile is applied automatically when the interface connects",

    "网卡配置": "Profiles",
    "每个接口下可以保存多份配置，其中最多只有一份能标记为「自动应用」": "You can save multiple profiles per interface, but only one can be marked Auto Apply.",
    "还没有保存任何配置，点下面的按钮新建一份": "No profiles saved yet. Click the button below to create one.",
    "无可写入的网络服务": "No writable network service",
    "删除配置": "Delete Profile",
    "移入回收站": "Move to Trash",
    "确定要把「%@」移入回收站吗？%d 天后会自动彻底删除。": "Move \"%@\" to the trash? It will be deleted permanently after %d days.",
    "已把「%@」移入回收站，%d 天后彻底删除": "Moved \"%@\" to the trash; it will be deleted permanently in %d days.",
    "自动应用": "Auto Apply",
    "生效中": "Active",
    "配置有误": "Invalid",
    "接口连上时自动应用这套配置。同一接口下只能有一份开启。": "Automatically apply this profile when the interface connects. Only one profile per interface can have this on.",
    "立即应用这套配置": "Apply this profile now",
    "检查静态路由是否已生效": "Check whether the static routes are in effect",
    "编辑": "Edit",
    "克隆一份": "Duplicate",
    "正在检查…": "Checking…",
    "没有配置静态路由": "No static routes configured",
    "无静态路由": "No static routes",
    "%d 条静态路由": "%d static routes",
    "网络优先级": "Network Priority",
    "系统按「网络服务优先级」决定用哪条链路收发数据。这份配置置顶后，插上网线就走它，不必先关掉 Wi-Fi": "The system uses the Network Service Priority order to decide which link carries traffic. With this profile promoted, plugging in the cable is enough — no need to turn Wi-Fi off first.",
    "应用时把该接口提到最前面": "Move this interface to the top when applying",
    "关闭时不动系统的服务顺序，只写 IP、DNS 和路由": "When off, the system's service order is left alone; only IP, DNS and routes are written.",
    "还没绑定接口，绑定之后才知道要把哪一项排到最前面": "No interface bound yet — bind one to know which service should move to the top.",
    "应用时把「%@」排到服务顺序第一位，其他服务的相对顺序不变": "On apply, \"%@\" moves to the first position in the service order; the other services keep their relative order.",
    "置顶": "Top",

    // MARK: - 回收站
    "回收站": "Trash",
    "删除的配置先放在这里，超过 %d 天才真的从磁盘上删掉": "Deleted profiles stay here for %d days before they are removed from disk.",
    "共 %d 份": "%d in total",
    "还剩 %d 天": "%d days left",
    "已过期，马上清理": "Expired, will be cleaned up shortly",
    "还原": "Restore",
    "已还原配置「%@」": "Restored profile \"%@\"",
    "接口 %@ 上已经有自动应用的「%@」，还原的这份不自动应用": "Interface %@ already has an auto-apply profile \"%@\"; the restored one will not auto-apply.",
    "彻底删除": "Delete Permanently",
    "彻底删除，不再恢复": "Delete permanently; this cannot be undone",
    "确定要彻底删除「%@」吗？这一步不能撤销。": "Permanently delete \"%@\"? This cannot be undone.",
    "已彻底删除「%@」": "Permanently deleted \"%@\"",
    "清空回收站": "Empty Trash",
    "会彻底删除里面全部 %d 份配置，此操作不能撤销。": "This permanently deletes all %d profiles in the trash and cannot be undone.",
    "已清空回收站，彻底删除 %d 份配置": "Emptied the trash, permanently deleting %d profiles.",
    "回收站里有 %d 份配置超过 %d 天，已彻底删除": "%d profiles in the trash passed the %d-day limit and were permanently deleted.",
]
