import Foundation

/// 「检查更新 / 下载安装 / 回退」相关文案的英文对照。键是中文原文。
let englishStringsUpdate: [String: String] = [
    // MARK: - 设置 / 更新
    "更新": "Updates",
    "启动后自动查一次，也可以随时手动查。只是向 GitHub 问一下版本号，不上传任何东西": "Checks once at launch and whenever you ask. It only asks GitHub for the version number and uploads nothing.",
    "SwitchNetwork %@": "SwitchNetwork %@",
    "配置共 %d 份": "%d profiles",
    "检查更新": "Check for Updates",
    "回退到上一个版本": "Roll Back to Previous Version",
    "下载并安装": "Download and Install",
    "打开发布页": "Open Release Page",

    // MARK: - 更新 / 状态
    "还没检查过": "Not checked yet",
    "正在检查有没有新版本…": "Checking for a new version…",
    "已经是最新版本（线上是 %@）": "You are up to date (latest is %@)",
    "已经是最新版本（检查于 %@）": "You are up to date (checked %@)",
    "检查于 %@": "Checked %@",
    "发现新版本 %@": "Version %@ is available",
    "启动时查到有新版本，点右边的按钮可以下载安装": "A new version was found at launch. Use the button on the right to download it.",
    "当前是 %@，装完会自动重新打开": "You are on %@. The app reopens itself once the update is installed.",
    "当前不是从「应用程序」里运行的，不能自动替换，请到发布页下载": "The app is not running from Applications, so it cannot replace itself. Download it from the release page instead.",
    "这个版本没有提供 dmg 附件，请到发布页下载": "This release has no dmg attachment; download it from the release page.",
    "替换过程中请不要退出应用": "Please do not quit the app while it is being replaced.",
    "正在下载新版本…": "Downloading the new version…",
    "正在校验安装包…": "Verifying the installer…",
    "正在替换应用…": "Replacing the app…",
    "正在重启…": "Restarting…",

    // MARK: - 更新 / 检查
    "更新地址不合法，检查更新暂时不可用": "The update address is invalid, so checking for updates is unavailable.",
    "连不上 GitHub：%@": "Cannot reach GitHub: %@",
    "仓库 %@ 还没有发布过版本": "Repository %@ has no releases yet",
    "GitHub 接口暂时不可用（多半是请求太频繁），过一会儿再试": "The GitHub API is unavailable right now (most likely rate limiting). Try again later.",
    "GitHub 返回了 %d": "GitHub returned %d",
    "GitHub 没有返回内容": "GitHub returned no content",
    "解析发布信息失败：%@": "Failed to parse the release information: %@",
    "发现新版本 %@，可在「设置 → 更新」里安装": "Version %@ is available; install it in Settings → Updates.",
    "发现新版本 %@，但这个版本没有 dmg 附件": "Version %@ is available, but that release has no dmg attachment.",
    "启动检查更新失败：%@": "The launch-time update check failed: %@",

    // MARK: - 更新 / 下载与安装
    "当前不是从「应用程序」里运行的，不能自我替换。请到发布页下载 dmg 手动安装。": "The app is not running from Applications, so it cannot replace itself. Download the dmg from the release page and install it manually.",
    "当前不是从「应用程序」里运行的，不能回退。": "The app is not running from Applications, so it cannot roll back.",
    "这个版本没有提供 dmg 附件，请到发布页下载。": "This release has no dmg attachment; download it from the release page.",
    "准备下载目录失败：%@": "Failed to prepare the download folder: %@",
    "下载失败：%@": "Download failed: %@",
    "下载没有返回文件": "The download returned no file",
    "下载返回了 %d": "The download returned %d",
    "下载到的文件是空的": "The downloaded file is empty",
    "下载到的文件校验和不一致，已放弃安装（多半是没下完）": "The downloaded file's checksum does not match; the install was cancelled (the download was most likely incomplete).",
    "这个版本没带校验和附件，跳过 SHA256 校验": "This release has no checksum attachment; skipping the SHA256 check.",
    "校验和附件是空的": "The checksum attachment is empty",
    "取校验和失败：HTTP %d": "Failed to fetch the checksum: HTTP %d",
    "取校验和没有返回内容": "Fetching the checksum returned no content",
    "取校验和失败": "Failed to fetch the checksum",
    "打开安装包失败：%@": "Failed to open the installer: %@",
    "卸载安装包失败：%@": "Failed to unmount the installer: %@",
    "安装包里没有找到 SwitchNetwork.app": "SwitchNetwork.app was not found in the installer",
    "安装包里的 app 读不出来": "The app inside the installer cannot be read",
    "安装包里的不是 SwitchNetwork": "The app inside the installer is not SwitchNetwork",
    "安装包里的版本是 %@，和要装的 %@ 对不上": "The installer contains version %@, which does not match the %@ being installed",
    "签名校验没通过：%@": "The signature check failed: %@",
    "没有权限写入「应用程序」文件夹，请下载 dmg 手动安装。": "No permission to write to the Applications folder. Download the dmg and install it manually.",
    "复制新版本失败：%@": "Failed to copy the new version: %@",
    "腾出原来那份应用失败：%@": "Failed to move the current app aside: %@",
    "放入新版本失败：%@": "Failed to put the new version in place: %@",
    "替换应用失败：%@": "Failed to replace the app: %@",
    "回退失败：%@": "Rollback failed: %@",
    "上一个版本的备份读不出来，回退已取消。": "The previous version's backup cannot be read; the rollback was cancelled.",
    "上一个版本的备份不是完整的 SwitchNetwork，回退已取消。": "The previous version's backup is not a complete SwitchNetwork; the rollback was cancelled.",
    "旧版本没能留成备份，这次没有回退可用：%@": "The old version could not be kept as a backup, so no rollback is available this time: %@",
    "重启失败，请手动打开应用：%@": "Failed to restart; please open the app manually: %@"
]
